@startuml "Corporativo"
'skinparam actorStyle awesome
'skinparam linetype ortho
left to right direction

actor Corporativo as C

usecase "Ver Perfil" as verPerfil
usecase "Personalizar Perfil" as personalizarPerfil
usecase "Enviar Mensagem" as enviarMensagem
usecase "Pesquisar Perfil" as pesquisarPerfil
usecase "Adicionar Perfil aos Favoritos" as adicionarFavoritos
usecase "Alterar Descrição" as alterarDescricao
usecase "Alterar Informações de Funcionamento" as alterarFuncionamento
usecase "Checar Agenda" as checarAgenda
usecase "Alterar Agenda" as alterarAgenda
usecase "Efetuar Pagamento" as efetuarPagamento
usecase "Criar Serviço" as criarServico
usecase "Aceitar Serviço" as aceitarServico
usecase "Cancelar Serviço" as cancelarServico
usecase "Avaliar Serviço" as avaliarServico
usecase "Bloquear Usuário" as bloquearUsuario
usecase "Cadastrar Estabelecimento" as cadastrarEstabelecimento

C --> verPerfil
C --> personalizarPerfil
'personalizarPerfil --> alterarDescricao
'personalizarPerfil --> alterarFuncionamento
verPerfil --> checarAgenda
checarAgenda <.. alterarAgenda : <<extend>>
checarAgenda <.. aceitarServico : <<extend>>
checarAgenda <.. cancelarServico : <<extend>>
checarAgenda <.. avaliarServico : <<extend>>
aceitarServico ..> efetuarPagamento : <<include>>
C --> pesquisarPerfil
verPerfil <.. adicionarFavoritos : <<extend>>
verPerfil <.. enviarMensagem : <<extend>>
verPerfil <.. criarServico : <<extend>>
verPerfil <.. bloquearUsuario : <<extend>>
C --> cadastrarEstabelecimento

personalizarPerfil <.. alterarDescricao : <<extend>>
personalizarPerfil <.. alterarFuncionamento : <<extend>>

@enduml