@startuml "Corporativo"
'skinparam actorStyle awesome
'skinparam linetype ortho
left to right direction

actor Corporativo as C

usecase "Acessar Perfil" as acessarPerfil
usecase "Personalizar Perfil Pessoal" as personalizarPerfil
usecase "Enviar Mensagem Pessoal" as enviarMensagem
usecase "Pesquisar Perfil" as pesquisarPerfil
usecase "Adicionar Perfil aos Favoritos" as adicionarFavoritos
usecase "Alterar Descrição" as alterarDescricao
usecase "Checar Agenda" as checarAgenda
usecase "Alterar Agenda" as alterarAgenda
usecase "Criar Serviço" as criarServico
usecase "Aceitar Serviço" as aceitarServico
usecase "Cancelar Serviço" as cancelarServico
usecase "Avaliar Serviço" as avaliarServico

C --> acessarPerfil
C --> personalizarPerfil
C --> checarAgenda
C --> alterarAgenda
C --> aceitarServico
C --> cancelarServico
C --> avaliarServico
C --> pesquisarPerfil
C --> adicionarFavoritos
C --> enviarMensagem
C --> criarServico
C --> alterarDescricao

@enduml