@startuml "Artista"
'skinparam actorStyle awesome
'skinparam linetype ortho

actor Gratuito as G
actor Artista as A
'actor Corporativo as C
'actor Administrador as ADM

package LinkArts{
    usecase "Assinar Plano" as assinarPlano
    usecase "Ver Perfil" as verPerfil
    usecase "Personalizar Perfil" as personalizarPerfil
    usecase "Enviar Mensagem" as enviarMensagem
    usecase "Pesquisar Perfil" as pesquisarPerfil
    usecase "Adicionar Perfil aos Favoritos" as adicionarFavoritos
    usecase "Alterar Música" as alterarMusica
    usecase "Registrar Música" as registrarMusica
    usecase "Apagar Música" as apagarMusica
    usecase "Adicionar Letra" as adicionarLetra
    usecase "Adicionar Audio" as adicionarAudio
    usecase "Adicionar Proficiências" as adicionarProf
    usecase "Alterar Descrição" as alterarDescricao
    usecase "Checar Agenda" as checarAgenda
    usecase "Alterar Agenda" as alterarAgenda
    usecase "Efetuar Pagamento" as efetuarPagamento
    usecase "Receber Pagamento" as receberPagamento
    usecase "Criar Serviço" as criarServico
    usecase "Aceitar Serviço" as aceitarServico
    usecase "Cancelar Serviço" as cancelarServico
    usecase "Avaliar Serviço" as avaliarServico
    usecase "Bloquear Usuário" as bloquearUsuario
    'usecase "Cadastrar Estabelecimento" as cadastrarEstabelecimento
    'usecase "Bloquear Conta" as bloquearConta
    'usecase "Banir Conta" as banirConta
    'usecase "Acessar Relatórios" as acessarRelatorio
    'usecase "Gerar Relatório" as gerarRelatorio
}

G --> assinarPlano
P --> verPerfil
verPerfil --> personalizarPerfil
personalizarPerfil --> alterarDescricao
personalizarPerfil --> adicionarProf
verPerfil --> registrarMusica
verPerfil --> checarAgenda
checarAgenda --> alterarAgenda
checarAgenda --> aceitarServico
checarAgenda --> cancelarServico
checarAgenda --> avaliarServico
registrarMusica --> alterarMusica
registrarMusica --> apagarMusica
registrarMusica --> adicionarLetra
registrarMusica --> adicionarAudio
P --> receberPagamento
P --> pesquisarPerfil
pesquisarPerfil --> adicionarFavoritos
pesquisarPerfil --> enviarMensagem
pesquisarPerfil --> criarServico
pesquisarPerfil --> bloquearUsuario

A <|-right- G

'C --> cadastrarEstabelecimento
'C --> efetuarPagamento

@enduml